"""comfyui-misc — ComfyUI カスタムノード（misc カテゴリ）と web/ フロントエンド拡張。"""
from .py.any_output_switch import NODE_CLASS_MAPPINGS as ANY_OUTPUT_SWITCH_MAPPINGS
from .py.any_output_switch import NODE_DISPLAY_NAME_MAPPINGS as ANY_OUTPUT_SWITCH_DISPLAY
from .py.any_switch import NODE_CLASS_MAPPINGS as ANY_SWITCH_MAPPINGS
from .py.any_switch import NODE_DISPLAY_NAME_MAPPINGS as ANY_SWITCH_DISPLAY
from .py.combine_primitives import NODE_CLASS_MAPPINGS as COMBINE_PRIMITIVES_MAPPINGS
from .py.combine_primitives import NODE_DISPLAY_NAME_MAPPINGS as COMBINE_PRIMITIVES_DISPLAY
from .py.foreach_primitives import NODE_CLASS_MAPPINGS as FOREACH_PRIMITIVES_MAPPINGS
from .py.foreach_primitives import NODE_DISPLAY_NAME_MAPPINGS as FOREACH_PRIMITIVES_DISPLAY
from .py.split_primitives import NODE_CLASS_MAPPINGS as SPLIT_PRIMITIVES_MAPPINGS
from .py.split_primitives import NODE_DISPLAY_NAME_MAPPINGS as SPLIT_PRIMITIVES_DISPLAY

NODE_CLASS_MAPPINGS = {
    **ANY_SWITCH_MAPPINGS,
    **ANY_OUTPUT_SWITCH_MAPPINGS,
    **COMBINE_PRIMITIVES_MAPPINGS,
    **FOREACH_PRIMITIVES_MAPPINGS,
    **SPLIT_PRIMITIVES_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **ANY_SWITCH_DISPLAY,
    **ANY_OUTPUT_SWITCH_DISPLAY,
    **COMBINE_PRIMITIVES_DISPLAY,
    **FOREACH_PRIMITIVES_DISPLAY,
    **SPLIT_PRIMITIVES_DISPLAY,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
